apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vr8ru12gw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vr8ru12gw-nodejs 
  name: vr8ru12gw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vr8ru12gw-nodejs 
